spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?serverTimezone=GMT%2B8
    username: root
    password: root
    schema-password: root
    schema-username: root
    schema: classpath:schema.sql
    data-username: root
    data-password: root
    data: classpath:data.sql
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver